var namespace_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories =
[
    [ "HunterItemFactory", "class_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories_1_1_hunter_item_factory.html", "class_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories_1_1_hunter_item_factory" ],
    [ "MageItemFactory", "class_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories_1_1_mage_item_factory.html", "class_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories_1_1_mage_item_factory" ],
    [ "WarriorItemFactory", "class_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories_1_1_warrior_item_factory.html", "class_mandatory2_d_game_framework_1_1_factory_1_1_abstract_factory_1_1_concrete_factories_1_1_warrior_item_factory" ]
];