var namespace_mandatory2_d_game_framework_1_1_decorator_1_1_interfaces =
[
    [ "IDefenceItem", "interface_mandatory2_d_game_framework_1_1_decorator_1_1_interfaces_1_1_i_defence_item.html", "interface_mandatory2_d_game_framework_1_1_decorator_1_1_interfaces_1_1_i_defence_item" ]
];